# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      coveralls_token: ${{ secrets.COVERALLS_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
            ~/.m2/repository
            ~/.sonar/cache
        key: ${{ runner.os }}-m2
    - name: Build with Maven
      run: ./mvnw -B verify -Prun-coverage
    - name: Report coverage
      run: ./mvnw -B coveralls:report -DrepoToken="${{ env.coveralls_token }}"
      if: ${{ github.repository_owner == 'jcgay' && github.actor != 'dependabot[bot]' }}
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
          java-version: 17
          distribution: 'temurin'
    - name: Analyze with sonarcloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=jcgay_maven-profiler -Dsonar.organization=jcgay-github -Dsonar.host.url=https://sonarcloud.io
      if: ${{ github.repository_owner == 'jcgay' && github.actor != 'dependabot[bot]' }}
